// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMsvyF7KTwOV8AxgvAO_0BYopNQqk5LtM',
    appId: '1:376530416779:web:955238377504529d55908e',
    messagingSenderId: '376530416779',
    projectId: 'appnotifications-28b81',
    authDomain: 'appnotifications-28b81.firebaseapp.com',
    storageBucket: 'appnotifications-28b81.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtyXGvZ5QSxWHtTB-e7h1SHyoGbDyC1aA',
    appId: '1:376530416779:android:28d4d32a308b2c2255908e',
    messagingSenderId: '376530416779',
    projectId: 'appnotifications-28b81',
    storageBucket: 'appnotifications-28b81.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9sDzS5f0cZekj2QzJU9rtpwO1eOfMMts',
    appId: '1:376530416779:ios:f156539346409c1355908e',
    messagingSenderId: '376530416779',
    projectId: 'appnotifications-28b81',
    storageBucket: 'appnotifications-28b81.appspot.com',
    iosClientId: '376530416779-6u3m1va7aqomld85qqkhl2idii4oobcj.apps.googleusercontent.com',
    iosBundleId: 'com.example.niserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9sDzS5f0cZekj2QzJU9rtpwO1eOfMMts',
    appId: '1:376530416779:ios:f156539346409c1355908e',
    messagingSenderId: '376530416779',
    projectId: 'appnotifications-28b81',
    storageBucket: 'appnotifications-28b81.appspot.com',
    iosClientId: '376530416779-6u3m1va7aqomld85qqkhl2idii4oobcj.apps.googleusercontent.com',
    iosBundleId: 'com.example.niserApp',
  );
}
