const String DOMAIN = "http://10.0.2.25:8000";
const String canteen_menu = "https://www.niser.ac.in/hostels/canteenmenu/";
const String timetable = "https://sdgniser.github.io/timetable/";
const String login = DOMAIN + "/login";
const String home = DOMAIN + "/";
const String arc = DOMAIN + "/arc";
const String listings = DOMAIN + "/listings";
const String lnf = DOMAIN + "/lnf";
const String profile = DOMAIN + "/profile";
